import Head from "next/head";
import Image from "next/image";
import Question from "./question";
import titanicPicture from "../public/titanic.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>LangChain & Titanic Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen py-2">
        <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
          <h1 className="text-6xl font-bold text-gray-500">
            The Titanic Database
          </h1>
          <Image
            width={250}
            height={250}
            src={titanicPicture}
            alt="Picture of the Titanic"
            className="rounded-sm border-2 border-gray-100 mt-8"
          />
          <Question />
        </main>
      </div>
    </>
  );
}
